### ISSUE TITLE
Popup flutterwave payment page

### ISSUE THREAD

**Issue by edfolmi** [yeboahd24/Django-Flutterwave#1]
I've did all the due processes and input my flutterwaves key, but the payment page is not popping.

**Comment by yeboahd24** [comment]
Hi, please what error are you getting.
Also have you check the latest flutterwave docs may be they might have updated it.

**Comment by edfolmi** [comment]
I was able to solve the issue and make the payment successful, but got JsonDecodeError when trying to save the whole details to my admin panel

**Comment by yeboahd24** [comment]
Okay, did you encode the response before saving it.

**Comment by edfolmi** [comment]
The verification is not working!

**Comment by edfolmi** [comment]
I've used a different approach, Acknowledge!
